services:
  - type: web
    name: ds-weather-disease
    env: docker
    plan: free
    autoDeploy: true
    branch: main
    healthCheckPath: /
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: "false"
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: "false"